### ISSUE TITLE
Doing a 1t walk hh is detected as a 2t hh

### ISSUE THREAD

**Issue by Elitemagikarp** [kurrycat2004/MpkMod#45] opened 2021-02-15 03:17 UTC
This probably happens for other walk timings too, I haven't tested them.

**Comment by kurrycat2004** [comment] 2021-02-15 10:41
Duplicate of #34
1.2.6 will have a complete rework of the last timing system that fixes that and other bugs

**Closed as completed** 2021-02-18 17:12 UTC
Labels: duplicate
